import { Car, Booking, Review, Location, RentalCompany } from './types';

export const companies: RentalCompany[] = [
  { id: 'c1', name: 'Elite Rentals', country: 'Israel' },
  { id: 'c2', name: 'Desert Drive', country: 'Israel' },
  { id: 'c3', name: 'Luxury Wheels', country: 'USA' },
  { id: 'c4', name: 'Empire Cars', country: 'USA' },
  { id: 'c5', name: 'Royal Fleet', country: 'UK' },
  { id: 'c6', name: 'London Luxury', country: 'UK' },
  { id: 'c7', name: 'Berlin Autobahn', country: 'Germany' },
  { id: 'c8', name: 'Parisian Prestige', country: 'France' },
  { id: 'c9', name: 'Roman Roads', country: 'Italy' },
];

export const locations: Location[] = [
  { id: '1', address: 'Ben Gurion Airport', city: 'Tel Aviv', country: 'Israel', latitude: 32.0055, longitude: 34.8854, companyId: 'c1' },
  { id: '2', address: 'King David St 23', city: 'Jerusalem', country: 'Israel', latitude: 31.7719, longitude: 35.2170, companyId: 'c1' },
  { id: '3', address: 'Haifa Port', city: 'Haifa', country: 'Israel', latitude: 32.8191, longitude: 34.9983, companyId: 'c2' },
  { id: '4', address: 'JFK Airport', city: 'New York', country: 'USA', latitude: 40.6413, longitude: -73.7781, companyId: 'c3' },
  { id: '5', address: 'LAX Airport', city: 'Los Angeles', country: 'USA', latitude: 33.9416, longitude: -118.4085, companyId: 'c3' },
  { id: '6', address: 'O\'Hare Airport', city: 'Chicago', country: 'USA', latitude: 41.9742, longitude: -87.9073, companyId: 'c4' },
  { id: '7', address: 'Heathrow Airport', city: 'London', country: 'UK', latitude: 51.4700, longitude: -0.4543, companyId: 'c5' },
  { id: '8', address: 'Manchester Airport', city: 'Manchester', country: 'UK', latitude: 53.3588, longitude: -2.2727, companyId: 'c5' },
  { id: '9', address: 'Berlin Brandenburg Airport', city: 'Berlin', country: 'Germany', latitude: 52.3667, longitude: 13.5033, companyId: 'c7' },
  { id: '10', address: 'Munich Airport', city: 'Munich', country: 'Germany', latitude: 48.3537, longitude: 11.7750, companyId: 'c7' },
  { id: '11', address: 'Charles de Gaulle Airport', city: 'Paris', country: 'France', latitude: 49.0097, longitude: 2.5479, companyId: 'c8' },
  { id: '12', address: 'Rome Fiumicino Airport', city: 'Rome', country: 'Italy', latitude: 41.7999, longitude: 12.2462, companyId: 'c9' },
];

export const cars: Car[] = [
  {
    car_id: '1',
    brand: 'Tesla',
    model: 'Model S Plaid',
    year: 2024,
    car_type: 'Electric',
    transmission_type: 'Automatic',
    seats_number: 5,
    trunk_capacity: '793L',
    car_features: ['Autopilot', 'Ludicrous Mode', '17" Touchscreen', 'Premium Sound'],
    price_per_day: 350,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
  },
  {
    car_id: '2',
    brand: 'Jeep',
    model: 'Rubicon',
    year: 2023,
    car_type: 'SUV',
    transmission_type: 'Automatic',
    seats_number: 5,
    trunk_capacity: '897L',
    car_features: ['4WD', 'Removable Top', 'Off-road Tires', 'Winch Ready'],
    price_per_day: 180,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
  },
  {
    car_id: '3',
    brand: 'Porsche',
    model: 'Carrera S',
    year: 2024,
    car_type: 'Sports',
    transmission_type: 'Automatic',
    seats_number: 2,
    trunk_capacity: '132L',
    car_features: ['Sport Chrono', 'Active Suspension', 'Launch Control', 'Bose Audio'],
    price_per_day: 550,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
  },
  {
    car_id: '4',
    brand: 'Toyota',
    model: 'Hybrid XSE',
    year: 2023,
    car_type: 'SUV',
    transmission_type: 'Automatic',
    seats_number: 5,
    trunk_capacity: '1059L',
    car_features: ['Hybrid Efficiency', 'AWD', 'Apple CarPlay', 'Lane Departure Warning'],
    price_per_day: 110,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?auto=format&fit=crop&q=80&w=800',
  },
  {
    car_id: '5',
    brand: 'BMW',
    model: '760i xDrive',
    year: 2024,
    car_type: 'Luxury',
    transmission_type: 'Automatic',
    seats_number: 5,
    trunk_capacity: '515L',
    car_features: ['Executive Lounge', '31" Theater Screen', 'Crystal Controls', 'Massage Seats'],
    price_per_day: 400,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=800',
  },
  {
    car_id: '6',
    brand: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2024,
    car_type: 'SUV',
    transmission_type: 'Automatic',
    seats_number: 5,
    trunk_capacity: '667L',
    car_features: ['V8 Bi-Turbo', 'Triple Diff Locks', 'Burmester Sound', 'Ambient Lighting'],
    price_per_day: 650,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&q=80&w=800',
    isBestSeller: true,
  },
  {
    car_id: '7',
    brand: 'Audi',
    model: 'A8 L',
    year: 2024,
    car_type: 'Luxury',
    transmission_type: 'Automatic',
    seats_number: 4,
    trunk_capacity: '505L',
    car_features: ['Quattro AWD', 'OLED Taillights', 'Rear Seat Entertainment', 'Bang & Olufsen'],
    price_per_day: 380,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1606148664061-a961cac77f49?auto=format&fit=crop&q=80&w=800',
  },
  {
    car_id: '8',
    brand: 'Volkswagen',
    model: 'Golf R',
    year: 2023,
    car_type: 'Compact',
    transmission_type: 'Manual',
    seats_number: 5,
    trunk_capacity: '374L',
    car_features: ['Drift Mode', 'Performance Exhaust', 'Digital Cockpit', 'Heated Seats'],
    price_per_day: 120,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=800',
  },
  {
    car_id: '9',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2024,
    car_type: 'Sports',
    transmission_type: 'Automatic',
    seats_number: 2,
    trunk_capacity: '272L',
    car_features: ['V8 Turbo', 'Carbon Fiber Interior', 'Passenger Display', 'Magneride Suspension'],
    price_per_day: 1200,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&q=80&w=800',
  },
  {
    car_id: '10',
    brand: 'Lucid',
    model: 'Air Sapphire',
    year: 2024,
    car_type: 'Electric',
    transmission_type: 'Automatic',
    seats_number: 5,
    trunk_capacity: '739L',
    car_features: ['Tri-Motor', '1200+ HP', 'Glass Canopy', 'DreamDrive Pro'],
    price_per_day: 450,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1669067038102-669460596956?auto=format&fit=crop&q=80&w=800',
  },
  {
    car_id: '11',
    brand: 'Honda',
    model: 'Civic Type R',
    year: 2024,
    car_type: 'Compact',
    transmission_type: 'Manual',
    seats_number: 4,
    trunk_capacity: '410L',
    car_features: ['VTEC Turbo', 'Brembo Brakes', 'LogR Data Logger', 'Sport Seats'],
    price_per_day: 150,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=80&w=800',
  },
  {
    car_id: '12',
    brand: 'Range Rover',
    model: 'Autobiography',
    year: 2024,
    car_type: 'SUV',
    transmission_type: 'Automatic',
    seats_number: 7,
    trunk_capacity: '818L',
    car_features: ['All-Wheel Steering', 'Meridian Signature Sound', 'Hot Stone Massage', 'Cabin Air Purification'],
    price_per_day: 500,
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1606611013016-969c19ba27bb?auto=format&fit=crop&q=80&w=800',
  },
];

export const bookings: Booking[] = [
  {
    booking_id: 'B1',
    car_id: '1',
    car_name: 'Tesla Model S',
    booking_date: '2024-03-01',
    pickup_date: '2024-03-10',
    return_date: '2024-03-12',
    pickup_location: locations[0],
    return_location: locations[0],
    total_price: 700,
    status: 'Confirmed',
  },
];

export const reviews: Review[] = [
  // Car 1
  { review_id: '1', car_id: '1', user_name: 'John Smith', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John', rating: 5, review_title: 'Future is here', comment: 'Amazing handling and the acceleration is just out of this world. Best electric car experience!', review_date: '2024-02-15' },
  { review_id: '2', car_id: '1', user_name: 'Sarah Wilson', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah', rating: 5, review_title: 'Incredible tech', comment: 'The autopilot works flawlessly on highways. Very comfortable for long trips.', review_date: '2024-01-20' },
  { review_id: '3', car_id: '1', user_name: 'Mike Ross', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike', rating: 4, review_title: 'Fast but quiet', comment: 'The silence is eerie at first but you get used to it. The performance is unmatched.', review_date: '2024-03-05' },
  // Car 2
  { review_id: '4', car_id: '2', user_name: 'David Brown', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David', rating: 5, review_title: 'Off-road beast', comment: 'Took it to the desert and it handled everything like a pro. Highly recommended!', review_date: '2024-02-10' },
  { review_id: '5', car_id: '2', user_name: 'Emma Davis', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma', rating: 4, review_title: 'Rugged and fun', comment: 'A bit noisy on the highway but that\'s expected. Great for adventure.', review_date: '2024-01-15' },
  { review_id: '6', car_id: '2', user_name: 'Chris Evans', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chris', rating: 5, review_title: 'Iconic look', comment: 'Nothing beats the feeling of driving a Jeep with the top off.', review_date: '2024-03-01' },
  // Car 3
  { review_id: '7', car_id: '3', user_name: 'James Bond', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', rating: 5, review_title: 'Pure adrenaline', comment: 'The engine sound is music to my ears. Precision engineering at its finest.', review_date: '2024-02-20' },
  { review_id: '8', car_id: '3', user_name: 'Linda White', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Linda', rating: 5, review_title: 'Dream car', comment: 'Handling is razor-sharp. It feels like it\'s on rails.', review_date: '2024-01-25' },
  { review_id: '9', car_id: '3', user_name: 'Robert Dow', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert', rating: 4, review_title: 'Stunning', comment: 'Turns heads everywhere I go. A bit tight on luggage space though.', review_date: '2024-03-10' },
  // Car 4
  { review_id: '10', car_id: '4', user_name: 'Alice Green', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice', rating: 5, review_title: 'Reliable and efficient', comment: 'Great fuel economy for an SUV. Very smooth ride.', review_date: '2024-02-05' },
  { review_id: '11', car_id: '4', user_name: 'Bob Miller', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob', rating: 4, review_title: 'Practical choice', comment: 'Perfect for the family. Plenty of room and very safe.', review_date: '2024-01-10' },
  { review_id: '12', car_id: '4', user_name: 'Charlie Black', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlie', rating: 5, review_title: 'Solid SUV', comment: 'Toyota reliability never disappoints. The hybrid system is seamless.', review_date: '2024-03-08' },
  // Car 5
  { review_id: '13', car_id: '5', user_name: 'Sophia Loren', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia', rating: 5, review_title: 'Ultimate luxury', comment: 'The theater screen in the back is incredible. It\'s a private jet on wheels.', review_date: '2024-02-28' },
  { review_id: '14', car_id: '5', user_name: 'George Clooney', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=George', rating: 5, review_title: 'Quiet and smooth', comment: 'You don\'t even feel the road. The massage seats are a game changer.', review_date: '2024-01-18' },
  { review_id: '15', car_id: '5', user_name: 'Brad Pitt', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Brad', rating: 5, review_title: 'Sophisticated', comment: 'The design is bold and the interior is pure class.', review_date: '2024-03-12' },
  // Car 6
  { review_id: '16', car_id: '6', user_name: 'Arnold S.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arnold', rating: 5, review_title: 'The King of SUVs', comment: 'Commanding presence on the road. The V8 sound is addictive.', review_date: '2024-02-12' },
  { review_id: '17', car_id: '6', user_name: 'Sylvester S.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sylvester', rating: 5, review_title: 'Unstoppable', comment: 'Feels like a tank but drives like a sports car. Amazing.', review_date: '2024-01-05' },
  { review_id: '18', car_id: '6', user_name: 'Jason S.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jason', rating: 4, review_title: 'Boxy but beautiful', comment: 'Classic design with modern tech. Very thirsty on fuel though.', review_date: '2024-03-15' },
  // Car 7
  { review_id: '19', car_id: '7', user_name: 'Tom Cruise', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tom', rating: 5, review_title: 'Tech masterpiece', comment: 'The lighting and screens are top notch. Very comfortable ride.', review_date: '2024-02-22' },
  { review_id: '20', car_id: '7', user_name: 'Nicole K.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nicole', rating: 5, review_title: 'Elegant', comment: 'Perfect for business trips. The rear seat space is generous.', review_date: '2024-01-12' },
  { review_id: '21', car_id: '7', user_name: 'Will Smith', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Will', rating: 4, review_title: 'Understated luxury', comment: 'Doesn\'t scream for attention but provides everything you need.', review_date: '2024-03-02' },
  // Car 8
  { review_id: '22', car_id: '8', user_name: 'Lewis H.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lewis', rating: 5, review_title: 'Pocket rocket', comment: 'So much fun to drive. The manual gearbox is very precise.', review_date: '2024-02-08' },
  { review_id: '23', car_id: '8', user_name: 'Max V.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Max', rating: 5, review_title: 'Daily driver', comment: 'Practical for city driving but has plenty of power when you need it.', review_date: '2024-01-28' },
  { review_id: '24', car_id: '8', user_name: 'Sebastian V.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sebastian', rating: 4, review_title: 'Great hatch', comment: 'The drift mode is a fun addition. Interior is a bit minimalist.', review_date: '2024-03-11' },
  // Car 9
  { review_id: '25', car_id: '9', user_name: 'Enzo F.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Enzo', rating: 5, review_title: 'La Dolce Vita', comment: 'Beautiful design and incredible performance. A true Ferrari.', review_date: '2024-02-14' },
  { review_id: '26', car_id: '9', user_name: 'Monica B.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Monica', rating: 5, review_title: 'Work of art', comment: 'Every detail is perfect. Driving it is a special occasion.', review_date: '2024-01-14' },
  { review_id: '27', car_id: '9', user_name: 'Leonardo D.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Leonardo', rating: 5, review_title: 'Exhilarating', comment: 'The acceleration and sound are intoxicating. Best car I\'ve ever rented.', review_date: '2024-03-04' },
  // Car 10
  { review_id: '28', car_id: '10', user_name: 'Elon M.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elon', rating: 5, review_title: 'Next level EV', comment: 'The range and power are industry leading. The glass roof is stunning.', review_date: '2024-02-18' },
  { review_id: '29', car_id: '10', user_name: 'Bill G.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bill', rating: 5, review_title: 'Impressive engineering', comment: 'Very efficient and the interior space is massive. Great tech.', review_date: '2024-01-08' },
  { review_id: '30', car_id: '10', user_name: 'Jeff B.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jeff', rating: 4, review_title: 'Luxury EV', comment: 'Feels more premium than a Tesla. The software is still maturing.', review_date: '2024-03-18' },
  // Car 11
  { review_id: '31', car_id: '11', user_name: 'Keanu R.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Keanu', rating: 5, review_title: 'Driver\'s car', comment: 'The manual shift is perfect. It handles like a dream on curvy roads.', review_date: '2024-02-25' },
  { review_id: '32', car_id: '11', user_name: 'Scarlett J.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Scarlett', rating: 5, review_title: 'Aggressive and fun', comment: 'Love the red interior and the wing. It\'s a head turner.', review_date: '2024-01-15' },
  { review_id: '33', car_id: '11', user_name: 'Ryan R.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ryan', rating: 4, review_title: 'Fast hatch', comment: 'A bit stiff for daily driving but amazing on the track.', review_date: '2024-03-05' },
  // Car 12
  { review_id: '34', car_id: '12', user_name: 'Queen E.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Queen', rating: 5, review_title: 'Majestic', comment: 'The pinnacle of SUV luxury. The ride quality is unparalleled.', review_date: '2024-02-10' },
  { review_id: '35', car_id: '12', user_name: 'Prince W.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Prince', rating: 5, review_title: 'Versatile', comment: 'Great for the family and for off-roading. Very capable.', review_date: '2024-01-20' },
  { review_id: '36', car_id: '12', user_name: 'Harry K.', user_avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Harry', rating: 5, review_title: 'Comfortable', comment: 'The sound system is the best I\'ve ever heard in a car.', review_date: '2024-03-10' },
];
