DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS BOOKING;
DROP TABLE IF EXISTS COMPANY_LOCATION;
DROP TABLE IF EXISTS CAR;
DROP TABLE IF EXISTS TOURIST;
DROP TABLE IF EXISTS LOCATION;
DROP TABLE IF EXISTS RENTAL_COMPANY;