/*******************************************************************************
                     Verification for fn_get_tourist_activity
*******************************************************************************/

-- Test Scenario 1: Normal Execution (Valid Tourist - e.g., ID 1)
-- Check the 'Messages' tab to see the custom printed data layout and expenditure log.
DO $$
DECLARE
    v_cursor REFCURSOR;
    r_review_id INT; r_title VARCHAR; r_score INT; r_type VARCHAR; r_branch VARCHAR; r_spend NUMERIC;
BEGIN
    RAISE NOTICE '=== TEST: FETCHING VALID TOURIST ACTIVITY ===';
    
    -- Call the function to retrieve the bound Ref Cursor
    v_cursor := public.fn_get_tourist_activity(1);
    
    -- Loop and fetch rows to output them to the Messages console
    LOOP
        FETCH NEXT FROM v_cursor INTO r_review_id, r_title, r_score, r_type, r_branch, r_spend;
        EXIT WHEN NOT FOUND;
        
        RAISE NOTICE 'Review ID: %, Title: %, Rating: % (%), Asset: %, Total Spend: %', 
                     r_review_id, r_title, r_score, r_type, r_branch, r_spend;
    END LOOP;
END $$;


-- Test Scenario 2: Error Handling & Boundary Condition (Non-Existent Tourist ID)
-- Check the 'Messages' tab to view the intercepted warning generated by the EXCEPTION block.
SELECT public.fn_get_tourist_activity(999999);